- hosts: all
  become: yes
  become_user: root
  vars:
    shadowsocks_port: 443
    shadowsocks_pwd: "{{ shadowsockspwd }}"
    shadowsocks_cipher: 'chacha20'
    shadowsocks_protocol: 'auth_sha1_v4_compatible'
    shadowsocks_obfs: 'http_simple_compatible'
    libsodium_version: '1.0.17'
    shadowsocks_r_version: '3.2.2'
    sysctl_config:
      net.core.default_qdisc: 'fq'
      net.ipv4.tcp_congestion_control: 'bbr'
      fs.file-max: 51200
      net.core.rmem_max: 67108864
      net.core.wmem_max: 67108864
      net.core.netdev_max_backlog: 250000
      net.core.somaxconn: 4096
      net.ipv4.tcp_syncookies: 1
      net.ipv4.tcp_tw_reuse: 1
      #net.ipv4.tcp_tw_recycle: 0
      net.ipv4.tcp_fin_timeout: 30
      net.ipv4.tcp_keepalive_time: 1200
      net.ipv4.ip_local_port_range: 10000 65000
      net.ipv4.tcp_max_syn_backlog: 8192
      net.ipv4.tcp_max_tw_buckets: 5000
      net.ipv4.tcp_fastopen: 3
      net.ipv4.tcp_mem: 25600 51200 102400
      net.ipv4.tcp_rmem: 4096 87380 67108864
      net.ipv4.tcp_wmem: 4096 65536 67108864
      net.ipv4.tcp_mtu_probing: 1

  tasks:
  - name: Set hostname 
    hostname: 
      name: "{{ hostname }}"
  - name: Kernel tweaks
    sysctl:
      name: '{{ item.key }}'
      value: '{{ item.value }}'
      state: present
      reload: yes
      ignoreerrors: yes
    with_dict: '{{ sysctl_config }}'
  - name: Update PAM limits  
    pam_limits:
      domain: '*'
      limit_type: '{{ item }}'
      limit_item: nofile
      value: '51200'
    loop:
      - soft
      - hard
  - name: Update PAM session modules  
    pamd:
      name: common-session
      new_type: session
      new_control: 'required'
      new_module_path: pam_limits.so
      state: after
      type: session
      control: optional
      module_path: pam_systemd.so
  - name: Install dependencies
    apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    loop:
      - python 
      - python-dev 
      - python-setuptools 
      - openssl 
      - libssl-dev 
      - curl 
      - wget 
      - unzip 
      - gcc 
      - automake 
      - autoconf 
      - make 
      - libtool

  - name: Download libsodium file
    get_url:
      url: "https://github.com/jedisct1/libsodium/releases/download/{{ libsodium_version }}/libsodium-{{ libsodium_version }}.tar.gz"
      dest: "/usr/local/src/libsodium-{{ libsodium_version }}.tar.gz"
  - name: Expand libsodium archive
    unarchive:
      src: "/usr/local/src/libsodium-{{ libsodium_version }}.tar.gz"
      dest: "/usr/local/src"
      creates: "/usr/local/src/libsodium-{{ libsodium_version }}/README"
      copy: false
  - name: Configure libsodium build
    command:
      chdir: "/usr/local/src/libsodium-{{ libsodium_version }}"
      cmd: ./configure --prefix=/usr
      creates: "/usr/local/src/libsodium-{{ libsodium_version }}/Makefile"
  - name: Build libsodium
    command: 
      chdir: "/usr/local/src/libsodium-{{ libsodium_version }}"
      cmd: make
      creates: "/usr/local/src/libsodium-{{ libsodium_version }}/src/libsodium/.libs/libsodium.a"
  - name: Install libsodium
    command:
      chdir: "/usr/local/src/libsodium-{{ libsodium_version }}"
      cmd: make install
      creates: /usr/lib/libsodium.a 
    notify:
        - Configure dynamic linker

  - name: Config ShadowsocksR
    template:
      src: templates/shadowsocks.json.j2
      dest: /etc/shadowsocks.json
  - name: Download ShadowsocksR
    get_url:
      url: "https://github.com/shadowsocksrr/shadowsocksr/archive/{{ shadowsocks_r_version }}.tar.gz"
      dest: "/usr/local/src/shadowsocksr-{{ shadowsocks_r_version }}.tar.gz"
  - name: Expand ShadowsocksR archive
    unarchive:
      src: "/usr/local/src/shadowsocksr-{{ shadowsocks_r_version }}.tar.gz"
      dest: "/usr/local/src"
      creates: "/usr/local/src/shadowsocksr-{{ shadowsocks_r_version }}/README.md" 
      copy: false
  - name: Install ShadowsocksR
    copy:
      remote_src: yes
      src: "/usr/local/src/shadowsocksr-{{ shadowsocks_r_version}}/shadowsocks"
      dest: "/usr/local/"
  - name: Download ShadowsocksR init script
    get_url: 
      url: https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocksR-debian
      dest: /etc/init.d/shadowsocks
      mode: '0755'
  - name: Install init script links
    command:
      cmd: update-rc.d -f shadowsocks defaults
      creates: /etc/rc0.d/K01shadowsocks
    notify:
      - Start shadowsocks

  handlers:
  - name: Configure dynamic linker
    command: 
      cmd: ldconfig
  - name: Start shadowsocks
    command:
      cmd: /etc/init.d/shadowsocks start

